### ISSUE TITLE
a{0,100}

### ISSUE THREAD

**Issue by gwlbrk** [bluezio/xeger#3]
Very simple issue. This code generates and print 30 times `a{0,100}`.

```
import nl.flotsam.xeger.Xeger;
class ExampleProgram {
   public static void main(String[] args){
	Xeger generator = new Xeger("a{0,100}"); 
	for (int i =0; i<30;++i)
		System.out.println(generator.generate());
   }
}

```
I would expect that some of the generated string are few characters long and some very long but all the string are very few characters (1-5 chars). Isn't this a bug?

Thank you, g.

**Comment by agarciadom** [comment]
You are asking for a string of "a"s between 0 and 100 characters long, and it's producing that, so I wouldn't call it a bug ;-). Rather than that, it's just a limitation of the available options to configure the random traversal of the finite state automaton created from the regexp. We just do a random walk, and we stop when we reach an "accept" state.

There is no option to tweak the minimum length of the random walk throughout the regular expression, and we offer no guarantees on the outputs being uniformly distributed over all possible strings. If we'd like to tweak the random walk, we'd need to implement those options. As a workaround, you could change the regexp to simply ask for a longer string, e.g. "a{10,100}".

Unfortunately, I have moved on to other projects and this is just a maintenance fork, so I do not have the time to do this. If you'd like to submit a pull request about this issue, I'd be happy to review it.

**Comment by gwlbrk** [comment]
Thank you for your quick answer bluezio. Unfortunately I cannot help, I don't know enough about automaton and I completely forget how to program in Java :) Thank you anyway!
Best regards, g.

**Comment by gwlbrk** [comment]
Well, if I'm not wrong, `a{n,m}` is `a{x}` where `x` is a random number between `n` and `m.` 

In other words, "somewhere" we could pre-process the regex expression and replace quantifier `{n,m}` to `{x}`.

This nice escamotage will not fix any bug, just guarantee a more nice distribution :) 

Unfortunately, I don't think I can do it in java.

**Comment by agarciadom** [comment]
This preprocessing would only work for really simple regexps, though, and it would really need to be configured explicitly, since otherwise we'd be the changing the behaviour that other users may rely upon.

I still think a flag for setting up a random-length walk (within two bounds) would probably be better than having this complex and limited preprocessing. We could simply add an alternative generate method that takes two arguments (min and max length), and tries to do a random walk of a random length between those bounds.

**Comment by gwlbrk** [comment]
My proposition is just an escamotage but probably it's better than nothing.
I post it here how I implemented in c#; it should be easy for a Java programmer convert it to Java. 

```
using System;
using System.Text.RegularExpressions;

namespace RegexQuantifier
{
    class Program
    {
        static string ConvertQuantifier(string input)
        //Convert a string containing any occurence of "{n,m}" in "{r}" with r=rnd(n,m);
        {
            string result = input;
            foreach (Match match in Regex.Matches(input, pattern: $@"\{{\s*\d+\s*,\s*\d+\s*\}}"))
            {
                string quantifier = match.Groups[0].Value;
                int min = int.Parse(Regex.Match(input: quantifier, pattern: $@"\d+").Value);
                int max = int.Parse(Regex.Match(input: quantifier, pattern: $@"\d+").NextMatch().Value);
                int r = new Random().Next(min, max + 1);
                result = Regex.Replace(input: result, pattern: quantifier, replacement: "{" + r.ToString() + "}");
            }
            return result;
        }
        static void Main(string[] args)
        {
            string input = "a{10 ,20} bill{ 0,   20} carl{3}";
            Console.WriteLine("Source string: " + input);
            Console.WriteLine("Output string: " + ConvertQuantifier(input));
        }
    }
}

```

My program probably contains few errors, it's surely not efficient and it could surely be better written.

Thank you Bluezio.
G.

**Comment by agarciadom** [comment]
Sorry, but again, this only works for your specific regexp. I cannot add
something that would be so limited in scope, and so hard to get fully right.

I have to insist on the alternative of having a method that instead focuses
on getting a random walk of a random length.

**Comment by gwlbrk** [comment]
Please delete my code if you think it is not useful (too specific etc.).

But could you explain a bit better why converting quantifier like {n.m} to {r} doesn't work always? My question is honest, I'm not a regex expert.
Thanks a lot!
g.

**Comment by agarciadom** [comment]
Sure :-). Regular expressions can be very complex, for instance
"(a[bc]{3,40})?xyz|ghi{0,10}.*hello". That's a valid regular expression,
but having something that can analyze it and decide what is the range of
the lengths of the random walks that you can generate from this regexp
would be very tricky.

Rather than that, I think it'd be a lot simpler if the user of Xeger (who
knows the characteristics of the regexp) would simply specify the range of
lengths of the random walks. The function doing the random walk when
requested with a random length between MIN and MAX steps would be:

1. Generate random length N = random(MIN, MAX).
2. Do a random walk over the regexp finite state machine over at most N
steps. (You may not reach N steps if you randomly walk into a state with no
outgoing transitions.)
3. If the current state of the FSM is an accept one, emit the string.
Otherwise, go back to step 2.

We would probably need to put a limit on the number of retries if we want
to ensure the function completes at some point in time, of course.

**Comment by agarciadom** [comment]
I've pushed an implementation of this method: please try it out when you can. I've kept the retrying out of the method: that's up to the caller. You can always catch the exception and then decide if you want to retry the walk or do something else.
